version: '3.8'  # Version du fichier de composition

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: nawres1011
      MYSQL_DATABASE: foyer
    ports:
      - "3308:3306"  # Exposer le port 3306 à l'extérieur via 3308
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - foyer-network

  springboot:
    build: .
    depends_on:
      - mysql
    command: ["./wait-for-it.sh", "mysql:3306", "java", "-jar", "app.jar"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/foyer?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: nawres1011
    ports:
      - "8081:8080"  # Mappage entre le port externe 8081 et le port interne 8080
    networks:
      - foyer-network

  sonarqube:
    image: sonarqube
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    ports:
      - "9004:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - foyer-network

  nexus:
    image: sonatype/nexus3
    ports:
      - "8084:8081"  # Expose Nexus on port 8084
    volumes:
      - nexus_data:/nexus-data
    networks:
      - foyer-network

networks:
  foyer-network:

volumes:
  mysql_data:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  nexus_data:
